import { defineTable } from 'convex/server'
import { v } from 'convex/values'

// REPORTING & ANALYTICS.
// Catchwatch (catch rates / remaining TAC), daily over-quota, and ad-hoc
// reports. Generated by scheduled functions (convex/crons.ts) + durable
// workflows; report lines mirror the real published Catchwatch columns.
export const reportingTables = {
  reportDefinitions: defineTable({
    code: v.union(
      v.literal('catchwatch'),
      v.literal('over_quota'),
      v.literal('ad_hoc'),
    ),
    name: v.string(),
    fisheryId: v.optional(v.id('fisheries')),
    audience: v.union(
      v.literal('public'),
      v.literal('industry'),
      v.literal('compliance'),
      v.literal('managers'),
    ),
    scheduleCron: v.optional(v.string()),
    isPublic: v.boolean(),
  }).index('by_code', ['code']),

  reportRuns: defineTable({
    definitionId: v.id('reportDefinitions'),
    periodFrom: v.number(),
    periodTo: v.number(),
    generatedAt: v.optional(v.number()),
    status: v.union(
      v.literal('pending'),
      v.literal('generated'),
      v.literal('issued'),
      v.literal('failed'),
    ),
    outputStorageId: v.optional(v.id('_storage')),
    issuedAt: v.optional(v.number()),
  }).index('by_definition', ['definitionId']),

  // Mirrors Catchwatch columns: species x sector -> TAC / reported / remaining.
  reportLines: defineTable({
    runId: v.id('reportRuns'),
    speciesId: v.optional(v.id('species')),
    sector: v.optional(v.union(v.literal('TIB'), v.literal('TVH'))),
    tacTonnes: v.optional(v.number()),
    reportedCatchTonnes: v.optional(v.number()),
    remainingTacTonnes: v.optional(v.number()),
    pctCaughtOfTac: v.optional(v.number()),
    conversionFactor: v.optional(v.number()),
    suppressed: v.optional(v.boolean()), // < 5 boats: Information Disclosure Policy
  }).index('by_run', ['runId']),
}
