import { For, Show } from 'solid-js'
import type { JSX } from '@solidjs/web'
import { cn } from './cn'

// Carousel — a swipeable, scroll-snapped rail whose dots and prev/next buttons
// are generated by the BROWSER (::scroll-marker / ::scroll-button), so it's
// accessible and effectively JS-free (Chrome 135+/Safari 26), degrading to a
// plain horizontal scroll everywhere else. The centred item tags itself "live"
// via @container scroll-state(snapped) — no scroll listener.
//
// On mobile this is the natural gesture for onboarding ("what you'll need"),
// browsing CAAB species, or stepping through guidance.

export function Carousel(props: {
	children: JSX.Element
	/** Show the generated dot markers below the rail (default true). */
	markers?: boolean
	class?: string
}): JSX.Element {
	return (
		<ul class={cn('tide-carousel', props.markers === false && 'tide-carousel-nomarkers', props.class)}>
			{props.children}
		</ul>
	)
}

export function CarouselSlide(props: {
	children: JSX.Element
	/** Gradient endpoints for the slide surface. */
	from?: string
	to?: string
	/** A small "in view" badge on the centred slide. */
	liveBadge?: JSX.Element
	class?: string
}): JSX.Element {
	return (
		<li
			class={cn('tide-slide', props.class)}
			style={{ '--from': props.from ?? 'var(--c-sea)', '--to': props.to ?? 'var(--c-sea-deep)' }}
		>
			<Show when={props.liveBadge}>
				<span class="tide-slide-live" aria-hidden="true">
					{props.liveBadge}
				</span>
			</Show>
			{props.children}
		</li>
	)
}

// A convenience for the common "image/illustration + caption" onboarding slide.
export function CarouselCards<T>(props: {
	items: T[]
	from?: (item: T, i: number) => string
	to?: (item: T, i: number) => string
	children: (item: T, i: number) => JSX.Element
	class?: string
}): JSX.Element {
	return (
		<Carousel class={props.class}>
			<For each={props.items}>
				{(item, i) => (
					<CarouselSlide from={props.from?.(item, i())} to={props.to?.(item, i())}>
						{props.children(item, i())}
					</CarouselSlide>
				)}
			</For>
		</Carousel>
	)
}
