/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedMyDataRouteImport } from './routes/_authed/my-data'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedConfirmRouteImport } from './routes/_authed/confirm'
import { Route as AuthedApplyRouteImport } from './routes/_authed/apply'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMyDataRoute = AuthedMyDataRouteImport.update({
  id: '/my-data',
  path: '/my-data',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConfirmRoute = AuthedConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplyRoute = AuthedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ui': typeof UiRoute
  '/apply': typeof AuthedApplyRoute
  '/confirm': typeof AuthedConfirmRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-data': typeof AuthedMyDataRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ui': typeof UiRoute
  '/apply': typeof AuthedApplyRoute
  '/confirm': typeof AuthedConfirmRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-data': typeof AuthedMyDataRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/ui': typeof UiRoute
  '/_authed/apply': typeof AuthedApplyRoute
  '/_authed/confirm': typeof AuthedConfirmRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/my-data': typeof AuthedMyDataRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ui'
    | '/apply'
    | '/confirm'
    | '/dashboard'
    | '/my-data'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ui'
    | '/apply'
    | '/confirm'
    | '/dashboard'
    | '/my-data'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/ui'
    | '/_authed/apply'
    | '/_authed/confirm'
    | '/_authed/dashboard'
    | '/_authed/my-data'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  UiRoute: typeof UiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/my-data': {
      id: '/_authed/my-data'
      path: '/my-data'
      fullPath: '/my-data'
      preLoaderRoute: typeof AuthedMyDataRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/confirm': {
      id: '/_authed/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof AuthedConfirmRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apply': {
      id: '/_authed/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthedApplyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedApplyRoute: typeof AuthedApplyRoute
  AuthedConfirmRoute: typeof AuthedConfirmRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMyDataRoute: typeof AuthedMyDataRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApplyRoute: AuthedApplyRoute,
  AuthedConfirmRoute: AuthedConfirmRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMyDataRoute: AuthedMyDataRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  UiRoute: UiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
